console.log("Notifications script loaded ✅");if("serviceWorker" in navigator){window.addEventListener("load",()=>{navigator.serviceWorker.register("/service-worker.js").then((reg)=>console.log("Service Worker مسجل بنجاح:",reg)).catch((err)=>console.error("فشل تسجيل Service Worker:",err))})}
function sendNotification(title,body,url){if("serviceWorker" in navigator){navigator.serviceWorker.ready.then((registration)=>{registration.showNotification(title,{body:body,icon:"/img/icon-192.png",badge:"/img/icon-192.png",vibrate:[200,100,200],data:{url:url},})})}else{new Notification(title,{body:body,icon:"/img/icon-192.png"})}}
function playAzanSound(){const azanAudio=new Audio("/img/adhan.mp3");azanAudio.play().catch((err)=>console.log("المتصفح منع التشغيل التلقائي للصوت:",err))}
const azkarList=["سبحان الله وبحمده","اللهم ارحم موتانا وموتى المسلمين","اللهم إنك عفو تحب العفو فاعف عنا","أستغفر الله العظيم","لا إله إلا الله وحده لا شريك له",];function firstRandomAzkar(){if(!sessionStorage.getItem("firstVisitThisSession")){const randomZikr=azkarList[Math.floor(Math.random()*azkarList.length)];const options={body:randomZikr,icon:"/img/icon-192.png",badge:"/img/icon.webp",};if(Notification.permission==="granted"){new Notification("ذكر اليوم 🌙",options)}
sessionStorage.setItem("firstVisitThisSession","true")}}
function hourlyAzkar(){const msg=azkarList[Math.floor(Math.random()*azkarList.length)];sendNotification("ذكر الساعة 🌙",msg,"/azkar")}
setInterval(hourlyAzkar,1000*60*60);function scheduleNotification(title,body,hour,minute,url){const now=new Date();const target=new Date();target.setHours(hour,minute,0,0);let diff=target-now;if(diff<0)diff+=24*60*60*1000;setTimeout(()=>{sendNotification(title,body,url);setInterval(()=>sendNotification(title,body,url),24*60*60*1000)},diff)}
function scheduleDailyAzkar(){scheduleNotification("أذكار الصباح 🌅","اذكار الصباح: سبحان الله، الحمد لله ...",6,0,"/azkar",);scheduleNotification("أذكار المساء 🌙","اذكار المساء: أستغفر الله، اللهم صل على النبي ...",18,0,"/azkar",)}
let currentPrayerTimes=null;let lastNotifiedPrayer=null;function setupPrayerNotifications(prayerTimes){if(Notification.permission!=="granted")return;currentPrayerTimes=prayerTimes;console.log("تم استلام مواقيت الصلاة وتفعيل المراقبة ✅")}
window.setupPrayerNotifications=setupPrayerNotifications;setInterval(()=>{if(!currentPrayerTimes)return;const now=new Date();const currentTimeString=now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",});Object.entries(currentPrayerTimes).forEach(([prayerName,timeObj])=>{const prayerDate=new Date(timeObj);const prayerTimeString=prayerDate.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",});if(currentTimeString===prayerTimeString&&lastNotifiedPrayer!==prayerName){lastNotifiedPrayer=prayerName;playAzanSound();if('serviceWorker' in navigator&&navigator.serviceWorker.controller){navigator.serviceWorker.controller.postMessage({type:"SHOW_PRAYER_NOTIFICATION",prayerName:prayerName})}}});if(now.getMinutes()===59){lastNotifiedPrayer=null}},30000);document.addEventListener("click",()=>{Notification.requestPermission().then((permission)=>{if(permission==="granted"){console.log("تم السماح بالإشعارات ✅");firstRandomAzkar();scheduleDailyAzkar()}})},{once:!0},)