(function(){'use strict';const API_SUWAR='../json/suwar.json';const API_RECITERS="../json/reciters.json";const STORAGE_RECITER='quran-sadaka-reciter';const STORAGE_MOSHAF='quran-sadaka-moshaf';const elReciter=document.getElementById('reciter');const elMoshaf=document.getElementById('moshaf');const elPlayerBar=document.getElementById('playerBar');const elPlayerSurahName=document.getElementById('playerSurahName');const elMainAudio=document.getElementById('mainAudio');const elLoading=document.getElementById('loading');const elErrorMsg=document.getElementById('errorMsg');const elSurahList=document.getElementById('surahList');const elBtnPrev=document.getElementById('btnPrev');const elBtnPlayPause=document.getElementById('btnPlayPause');const elBtnNext=document.getElementById('btnNext');const btnStop=document.getElementById("btnStop");const volumeSlider=document.getElementById("volumeSlider");const volumeIcon=document.getElementById("volumeIcon");const readProgressBar=document.getElementById("readProgressBar");const readProgressFill=document.getElementById("readProgressFill");const readProgressKnob=document.getElementById("readProgressKnob");const readCurrentTime=document.getElementById("readCurrentTime");const readDuration=document.getElementById("readDuration");const btnAutoReplay=document.getElementById("btnAutoReplay");let suwar=[];let reciters=[];let currentReciter=null;let currentMoshaf=null;let currentSurahId=null;let currentSurahName=null;let isAutoReplay=!1;function pad(num){return String(num).padStart(3,'0')}
function formatTime(time){if(isNaN(time))return"0:00";const minutes=Math.floor(time/60);const seconds=Math.floor(time%60);return `${minutes}:${seconds.toString().padStart(2, "0")}`}
function showError(msg){elLoading.style.display='none';elSurahList.innerHTML='';elErrorMsg.textContent=msg;elErrorMsg.style.display='block'}
function hideError(){elErrorMsg.style.display='none'}
function isSurahInList(surahId){if(!currentMoshaf||!currentMoshaf.surah_list)return!1;return currentMoshaf.surah_list.split(',').includes(String(surahId))}
function getAudioUrl(surahId){if(!currentMoshaf||!currentMoshaf.server||!isSurahInList(surahId))return null;const base=currentMoshaf.server.replace(/\/$/,'');return `${base}/${pad(surahId)}.mp3`}
function getPlayableSuwar(){if(!currentMoshaf)return[];return suwar.filter(s=>isSurahInList(s.id)).sort((a,b)=>a.id-b.id)}
function updateUIControls(){if(!elMainAudio.src)return;elBtnPlayPause.textContent=elMainAudio.paused?'▶':'⏸';const list=getPlayableSuwar();const idx=list.findIndex(s=>s.id===currentSurahId);elBtnPrev.disabled=idx<=0;elBtnNext.disabled=idx<0||idx>=list.length-1}
function loadSuwar(){return fetch(API_SUWAR).then(res=>res.json()).then(data=>{if(data.suwar){suwar=data.suwar;return suwar}
throw new Error('بيانات السور غير صالحة')})}
function loadReciters(){return fetch(API_RECITERS).then(res=>res.json()).then(data=>{if(data.reciters){reciters=data.reciters.map(r=>{if(r.moshaf&&r.moshaf.length){const hIdx=r.moshaf.findIndex(m=>m.name&&m.name.includes("حفص"));if(hIdx>0)r.moshaf.unshift(r.moshaf.splice(hIdx,1)[0]);}
return r});return reciters}
throw new Error('بيانات القراء غير صالحة')})}
function playSurah(surahId,surahName){const url=getAudioUrl(surahId);if(!url){alert('هذه السورة غير متوفرة لهذا القارئ حالياً.');return}
currentSurahId=surahId;currentSurahName=surahName||surahId;elPlayerSurahName.textContent='سورة '+currentSurahName;elMainAudio.src=url;elMainAudio.play().then(()=>{updateMediaSession()}).catch(e=>console.error("Playback failed:",e));elPlayerBar.style.display="grid";elPlayerBar.classList.add('active');btnStop.style.display="inline-block"}
function updateMediaSession(){if('mediaSession' in navigator){const reciterName=elReciter.options[elReciter.selectedIndex]?.text||'قارئ القرآن';navigator.mediaSession.metadata=new MediaMetadata({title:'سورة '+currentSurahName,artist:reciterName,album:'قرآن صدقة',artwork:[{src:'../img/icon.webp',sizes:'512x512',type:'image/webp'}]});navigator.mediaSession.playbackState='playing'}}
function playPrevious(){const list=getPlayableSuwar();const idx=list.findIndex(s=>s.id===currentSurahId);if(idx>0)playSurah(list[idx-1].id,list[idx-1].name);}
function playNext(){const list=getPlayableSuwar();const idx=list.findIndex(s=>s.id===currentSurahId);if(idx>=0&&idx<list.length-1)playSurah(list[idx+1].id,list[idx+1].name);}
elReciter.addEventListener('change',function(){const id=this.value;currentReciter=reciters.find(r=>String(r.id)===id)||null;elMoshaf.innerHTML='<option value="">-- نوع القراءة --</option>';if(currentReciter&&currentReciter.moshaf){currentReciter.moshaf.forEach((m,i)=>{const opt=document.createElement('option');opt.value=i;opt.textContent=m.name||'قراءة '+(i+1);elMoshaf.appendChild(opt)});elMoshaf.value='0';currentMoshaf=currentReciter.moshaf[0]}
localStorage.setItem(STORAGE_RECITER,id)});elMoshaf.addEventListener('change',function(){const idx=parseInt(this.value,10);currentMoshaf=(currentReciter&&currentReciter.moshaf)?currentReciter.moshaf[idx]:null;localStorage.setItem(STORAGE_MOSHAF,String(idx))});elBtnPlayPause.addEventListener('click',()=>{if(elMainAudio.paused)elMainAudio.play();else elMainAudio.pause()});elBtnPrev.addEventListener('click',playPrevious);elBtnNext.addEventListener('click',playNext);btnStop.addEventListener('click',()=>{elMainAudio.pause();elMainAudio.currentTime=0;if('mediaSession' in navigator)navigator.mediaSession.playbackState='none'});btnAutoReplay.addEventListener('click',()=>{isAutoReplay=!isAutoReplay;btnAutoReplay.style.color=isAutoReplay?"#27ae60":"inherit";btnAutoReplay.classList.toggle("activeBtn",isAutoReplay)});elMainAudio.addEventListener('play',()=>{updateUIControls();if('mediaSession' in navigator)navigator.mediaSession.playbackState='playing'});elMainAudio.addEventListener('pause',()=>{updateUIControls();if('mediaSession' in navigator)navigator.mediaSession.playbackState='paused'});elMainAudio.addEventListener('ended',()=>{if(isAutoReplay){elMainAudio.currentTime=0;elMainAudio.play()}else{playNext()}});elMainAudio.addEventListener('timeupdate',()=>{if(isNaN(elMainAudio.duration))return;const percent=(elMainAudio.currentTime/elMainAudio.duration)*100;readProgressFill.style.width=percent+"%";readProgressKnob.style.left=percent+"%";readCurrentTime.textContent=formatTime(elMainAudio.currentTime);readDuration.textContent=formatTime(elMainAudio.duration)});readProgressBar.addEventListener('click',(e)=>{const rect=readProgressBar.getBoundingClientRect();const offsetX=e.clientX-rect.left;const percent=offsetX/rect.width;if(!isNaN(elMainAudio.duration)){elMainAudio.currentTime=percent*elMainAudio.duration}});function setVolume(val){elMainAudio.volume=val;if(val===0)volumeIcon.textContent="🔇";else if(val<0.5)volumeIcon.textContent="🔉";else volumeIcon.textContent="🔊"}
volumeSlider.addEventListener('input',(e)=>setVolume(parseFloat(e.target.value)));volumeIcon.addEventListener('click',()=>volumeSlider.classList.toggle('show'));if('mediaSession' in navigator){navigator.mediaSession.setActionHandler('play',()=>elMainAudio.play());navigator.mediaSession.setActionHandler('pause',()=>elMainAudio.pause());navigator.mediaSession.setActionHandler('stop',()=>{elMainAudio.pause();elMainAudio.currentTime=0});navigator.mediaSession.setActionHandler('previoustrack',playPrevious);navigator.mediaSession.setActionHandler('nexttrack',playNext)}
Promise.all([loadSuwar(),loadReciters()]).then(()=>{const sorted=[...reciters].sort((a,b)=>a.name.localeCompare(b.name,'ar'));sorted.forEach(r=>{const opt=document.createElement('option');opt.value=r.id;opt.textContent=r.name;elReciter.appendChild(opt)});const savedR=localStorage.getItem(STORAGE_RECITER);const savedM=localStorage.getItem(STORAGE_MOSHAF);if(savedR){elReciter.value=savedR;elReciter.dispatchEvent(new Event('change'));if(savedM!==null){elMoshaf.value=savedM;elMoshaf.dispatchEvent(new Event('change'))}}
elLoading.style.display='none';suwar.forEach(s=>{const div=document.createElement('div');div.className='surah-item';const type=s.makkia===1?'مكية':'مدنية';div.innerHTML=`
        <span class="surah-num">${s.id}</span>
        <div class="surah-info">
          <span class="name-ar">${s.name}</span>
          <span class="name-en">${type}</span>
        </div>
        <span class="play-icon">▶</span>
      `;div.addEventListener('click',()=>playSurah(s.id,s.name));elSurahList.appendChild(div)})}).catch(err=>{showError('فشل تحميل البيانات. يرجى التأكد من الإنترنت.');console.error(err)})})()