document.addEventListener("DOMContentLoaded",function(){function updateRamadanCountdown(){const ramadanStart=new Date("2026-02-19T00:00:00");const ramadanEnd=new Date("2026-03-21T00:00:00");const now=new Date();const messageEl=document.getElementById("message");const countdownBox=document.getElementById("countdown");if(!messageEl)return;let target,message;if(now<ramadanStart){target=ramadanStart;message="متبقي حتى بداية رمضان 🌙"}else if(now>=ramadanStart&&now<=ramadanEnd){target=ramadanEnd;message="رمضان بدأ ✅ متبقي حتى نهاية رمضان"}else{messageEl.textContent="عيد فطر مبارك 😃🎈 🎉";if(countdownBox)countdownBox.style.display="none";return}
const diff=target-now;const days=Math.floor(diff/(1000*60*60*24));const hours=Math.floor((diff%(1000*60*60*24))/(1000*60*60));const minutes=Math.floor((diff%(1000*60*60))/(1000*60));document.getElementById("days").textContent=days;document.getElementById("hours").textContent=hours;document.getElementById("minutes").textContent=minutes;messageEl.textContent=message}
updateRamadanCountdown();setInterval(updateRamadanCountdown,60000);let countdownInterval=null;function getPrayerTimes(){const prayerMap={"الفجر":"Fajr","الشروق":"Sunrise","الظهر":"Dhuhr","العصر":"Asr","المغرب":"Maghrib","العشاء":"Isha"};const savedLat=localStorage.getItem("latitude");const savedLng=localStorage.getItem("longitude");const locationBtn=document.getElementById("locationBtn");if(savedLat&&savedLng){if(locationBtn)locationBtn.style.display="none";fetchPrayerTimes(savedLat,savedLng,prayerMap)}else{if(locationBtn){locationBtn.style.display="inline-block";locationBtn.onclick=()=>{navigator.geolocation.getCurrentPosition((pos)=>{const lat=pos.coords.latitude;const lng=pos.coords.longitude;localStorage.setItem("latitude",lat);localStorage.setItem("longitude",lng);locationBtn.style.display="none";fetchPrayerTimes(lat,lng,prayerMap)},()=>alert("تعذر الحصول على الموقع"))}}}}
function setupPrayerNotifications(prayerTimes){Object.entries(prayerTimes).forEach(([prayer,time])=>{const now=new Date();const[hour,minute]=time.split(":").map(Number);const prayerDate=new Date();prayerDate.setHours(hour,minute,0,0);const diff=prayerDate-now;if(diff>0){setTimeout(()=>{sendNotification(`وقت صلاة ${prayer} 🌙`,`الصلاة الآن ${time}`)},diff)}})}
function fetchPrayerTimes(lat,lng,prayerMap){fetch(`https://api.aladhan.com/v1/timings?latitude=${lat}&longitude=${lng}&method=5`).then((res)=>res.json()).then((data)=>{if(data.code!==200)return;const timings=data.data.timings;const prayerItems=document.querySelectorAll(".prayer-item");const prayerTimes={};prayerItems.forEach((item)=>{const arabicName=item.querySelector(".prayer-name").textContent;const engName=prayerMap[arabicName];if(!timings[engName])return;const time24=timings[engName].split(" ")[0];item.querySelector(".prayer-time").dataset.time24=time24;item.querySelector(".prayer-time").textContent=convertTo12Hour(time24);prayerTimes[arabicName]=time24});highlightNextPrayer();startNextPrayerCountdown();if(window.initNotifications)window.initNotifications(prayerTimes);}).catch((err)=>console.log(err))}
function convertTo12Hour(time24){let[hour,minute]=time24.split(":").map(Number);let suffix=hour>=12?"م":"ص";hour=((hour+11)%12+1);return hour+":"+(minute<10?"0"+minute:minute)+" "+suffix}
function getNextPrayer(){const now=new Date();const prayerItems=Array.from(document.querySelectorAll(".prayer-item"));for(let item of prayerItems){const time24=item.querySelector(".prayer-time").dataset.time24;if(!time24)continue;const[h,m]=time24.split(":").map(Number);const prayerDate=new Date();prayerDate.setHours(h,m,0,0);if(prayerDate>now){return{item,date:prayerDate}}}
const fajrTime=prayerItems[0].querySelector(".prayer-time").dataset.time24;const[h,m]=fajrTime.split(":").map(Number);const nextDay=new Date();nextDay.setDate(now.getDate()+1);nextDay.setHours(h,m,0,0);return{item:prayerItems[0],date:nextDay}}
function highlightNextPrayer(){document.querySelectorAll(".prayer-item").forEach(item=>item.classList.remove("next-prayer"));const next=getNextPrayer();if(next&&next.item){next.item.classList.add("next-prayer")}}
function startNextPrayerCountdown(){if(countdownInterval)clearInterval(countdownInterval);countdownInterval=setInterval(()=>{const next=getNextPrayer();if(!next)return;const now=new Date();const diff=next.date-now;const hours=Math.floor(diff/(1000*60*60));const minutes=Math.floor((diff%(1000*60*60))/(1000*60));const seconds=Math.floor((diff%(1000*60))/1000);const name=next.item.querySelector(".prayer-name").textContent;const countdownEl=document.getElementById("nextPrayerCountdown");if(countdownEl){countdownEl.textContent=`الصلاة القادمة: ${name} بعد ${hours} ساعة و ${minutes} دقيقة و ${seconds} ثانية`}
highlightNextPrayer()},1000)}
document.addEventListener("DOMContentLoaded",()=>{const locationBtn=document.getElementById("locationBtn");function initAppWithCoords(lat,lng){const prayerMap={"الفجر":"Fajr","الشروق":"Sunrise","الظهر":"Dhuhr","العصر":"Asr","المغرب":"Maghrib","العشاء":"Isha"};fetchPrayerTimes(lat,lng,prayerMap)}
if(navigator.geolocation){navigator.geolocation.getCurrentPosition((pos)=>{const lat=pos.coords.latitude;const lng=pos.coords.longitude;initAppWithCoords(lat,lng)},(err)=>{console.warn("رفض المستخدم الوصول للموقع، استخدم زر تحديد الموقع");if(locationBtn)locationBtn.style.display="inline-block"})}else{console.warn("Geolocation غير مدعوم في هذا المتصفح");if(locationBtn)locationBtn.style.display="inline-block"}
if(locationBtn){locationBtn.addEventListener("click",()=>{navigator.geolocation.getCurrentPosition((pos)=>{const lat=pos.coords.latitude;const lng=pos.coords.longitude;initAppWithCoords(lat,lng);locationBtn.style.display="none"},()=>alert("لا يمكن الوصول للموقع."))})}});getPrayerTimes()});document.querySelectorAll(".copy-btn").forEach(btn=>{btn.addEventListener("click",function(){const textToCopy=this.previousElementSibling.textContent;btn.textContent="تم النسخ ✅";setTimeout(()=>{btn.textContent="نسخ"},2000);if(!textToCopy)return;navigator.clipboard.writeText(textToCopy).catch((err)=>{console.error("خطأ في النسخ:",err);alert("حدث خطأ في النسخ، حاول مرة أخرى.")})})})